#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.19050
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SeligerApplication.Android.Resource", IsApplication=true)]

namespace SeligerApplication.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int l1artkvadrat = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int l1begizamnoy = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int l1komanda2018 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int l1tehnologiyadobra = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int l2infopotok = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int l2innovacii = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int l2molodejnoesamoupravlenie = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int l2predprinimatelstvo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int l2vsedoma = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int l3ecomol = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int l3ekonomikabuduchego = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int l3molodejniiturizm = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int l3molodiedizaineri = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int l3molodieuristi = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int l3regionirossii = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int l3selogerinternational = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int l3studencheskieorganizacii = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int l4bibliotekabuduchego = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int l4duhovnaiarossia = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int l4kazachiamolodej = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int l4patrioticheskieklubi = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int l4rabotauchayamolodej = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int l4russkayapravda = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int l4uchitelbuduchego = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int l4vdvigenii = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int Text1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainHeaders = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainSections = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SimpleListItem1 = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
